#############################################################################
# Makefile for building: LOPATool.app/Contents/MacOS/LOPATool
# Generated by qmake (3.1) (Qt 6.1.2)
# Project:  LOPATool.pro
# Template: app
# Command: /opt/homebrew/bin/qmake -o Makefile LOPATool.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/macx-clang -F/opt/homebrew/Cellar/qt/6.1.2/lib
QMAKE         = /opt/homebrew/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = LOPATool1.0.0
DISTDIR = /Users/sheetal/LOPATool/.tmp/LOPATool1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/opt/homebrew/Cellar/qt/6.1.2/lib
LIBS          = $(SUBLIBS) -F/opt/homebrew/Cellar/qt/6.1.2/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtSql -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = databaseutils.cpp \
		main.cpp \
		lopatool.cpp \
		newprojectwindow.cpp qrc_assets.cpp \
		moc_lopatool.cpp \
		moc_newprojectwindow.cpp
OBJECTS       = databaseutils.o \
		main.o \
		lopatool.o \
		newprojectwindow.o \
		qrc_assets.o \
		moc_lopatool.o \
		moc_newprojectwindow.o
DIST          = /opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/lex.prf \
		LOPATool.pro databaseutils.h \
		lopatool.h \
		newprojectwindow.h databaseutils.cpp \
		main.cpp \
		lopatool.cpp \
		newprojectwindow.cpp
QMAKE_TARGET  = LOPATool
DESTDIR       = 
TARGET        = LOPATool.app/Contents/MacOS/LOPATool

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/sheetal/LOPATool/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/sheetal/LOPATool/LOPATool.pro


include /opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

LOPATool.app/Contents/MacOS/LOPATool: ui_lopatool.h ui_newprojectwindow.h $(OBJECTS)  
	@test -d LOPATool.app/Contents/MacOS/ || mkdir -p LOPATool.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LOPATool.pro /opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/macx-clang/qmake.conf /opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/lex.prf \
		LOPATool.pro \
		assets.qrc \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Resources/QtSql.prl \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile LOPATool.pro
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/spec_pre.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/device_config.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/unix.conf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/mac.conf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/macx.conf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/sanitize.conf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/gcc-base.conf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/gcc-base-mac.conf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/clang.conf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/common/clang-mac.conf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/qconfig.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3danimation.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dcore.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dextras.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dinput.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquick.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3drender.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_charts.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_charts_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_coap.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_coap_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_designer.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_designer_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_gui.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_help.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_help_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsanimation.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssettings.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_linguist.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_linguist_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_mqtt.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_network.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_networkauth.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opcua.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opcua_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qml.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3d.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxml.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_sql.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachine.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svg.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_tools_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_uitools.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_xml.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qt_functions.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qt_config.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/macx-clang/qmake.conf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/exclusive_builds.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/sdk.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/toolchain.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/toolchain.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/default_pre.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/default_pre.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/resolve_config.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/default_post.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/default_post.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/objective_c.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/mac.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/warn_on.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qt.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/resources_functions.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/resources.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/moc.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/unix/opengl.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/uic.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/unix/thread.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/qmake_use.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/file_copies.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/rez.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/testcase_targets.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/exceptions.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/yacc.prf:
/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/lex.prf:
LOPATool.pro:
assets.qrc:
/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/homebrew/Cellar/qt/6.1.2/lib/QtGui.framework/Resources/QtGui.prl:
/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Resources/QtSql.prl:
/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile LOPATool.pro

qmake_all: FORCE

LOPATool.app/Contents/PkgInfo: 
	@test -d LOPATool.app/Contents || mkdir -p LOPATool.app/Contents
	@$(DEL_FILE) LOPATool.app/Contents/PkgInfo
	@echo "APPL????" > LOPATool.app/Contents/PkgInfo
LOPATool.app/Contents/Resources/empty.lproj: 
	@test -d LOPATool.app/Contents/Resources || mkdir -p LOPATool.app/Contents/Resources
	@touch LOPATool.app/Contents/Resources/empty.lproj
	
LOPATool.app/Contents/Info.plist: 
	@test -d LOPATool.app/Contents || mkdir -p LOPATool.app/Contents
	@$(DEL_FILE) LOPATool.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.LOPATool,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.LOPATool,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,LOPATool,g" -e "s,@LIBRARY@,LOPATool,g" -e "s,\$${EXECUTABLE_NAME},LOPATool,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/macx-clang/Info.plist.app >LOPATool.app/Contents/Info.plist

all: Makefile \
		LOPATool.app/Contents/PkgInfo \
		LOPATool.app/Contents/Resources/empty.lproj \
		LOPATool.app/Contents/Info.plist LOPATool.app/Contents/MacOS/LOPATool

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents assets.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents databaseutils.h lopatool.h newprojectwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents databaseutils.cpp main.cpp lopatool.cpp newprojectwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents lopatool.ui newprojectwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r LOPATool.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_assets.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_assets.cpp
qrc_assets.cpp: assets.qrc \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/libexec/rcc \
		assets/Logo_Uni-Kassel.png
	/opt/homebrew/Cellar/qt/6.1.2/share/qt/libexec/rcc -name assets assets.qrc -o qrc_assets.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11 -Wall -Wextra -dM -E -o moc_predefs.h /opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_lopatool.cpp moc_newprojectwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_lopatool.cpp moc_newprojectwindow.cpp
moc_lopatool.cpp: lopatool.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/qmainwindow.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/libexec/moc
	/opt/homebrew/Cellar/qt/6.1.2/share/qt/libexec/moc $(DEFINES) --include /Users/sheetal/LOPATool/moc_predefs.h -I/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/macx-clang -I/Users/sheetal/LOPATool -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/opt/homebrew/Cellar/qt/6.1.2/lib lopatool.h -o moc_lopatool.cpp

moc_newprojectwindow.cpp: newprojectwindow.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlDatabase \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqldatabase.h \
		DatabaseUtils.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlDriver \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqldriver.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlError \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqlerror.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlQuery \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqlquery.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/QSettings \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/qsettings.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/qmap.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/libexec/moc
	/opt/homebrew/Cellar/qt/6.1.2/share/qt/libexec/moc $(DEFINES) --include /Users/sheetal/LOPATool/moc_predefs.h -I/opt/homebrew/Cellar/qt/6.1.2/share/qt/mkspecs/macx-clang -I/Users/sheetal/LOPATool -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers -I/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/opt/homebrew/Cellar/qt/6.1.2/lib newprojectwindow.h -o moc_newprojectwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_lopatool.h ui_newprojectwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_lopatool.h ui_newprojectwindow.h
ui_lopatool.h: lopatool.ui \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/libexec/uic
	/opt/homebrew/Cellar/qt/6.1.2/share/qt/libexec/uic lopatool.ui -o ui_lopatool.h

ui_newprojectwindow.h: newprojectwindow.ui \
		/opt/homebrew/Cellar/qt/6.1.2/share/qt/libexec/uic
	/opt/homebrew/Cellar/qt/6.1.2/share/qt/libexec/uic newprojectwindow.ui -o ui_newprojectwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

databaseutils.o: databaseutils.cpp databaseutils.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlDatabase \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqldatabase.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlDriver \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqldriver.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlError \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqlerror.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlQuery \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqlquery.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/QSettings \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/qsettings.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/qmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databaseutils.o databaseutils.cpp

main.o: main.cpp lopatool.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/QApplication \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

lopatool.o: lopatool.cpp lopatool.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_lopatool.h \
		newprojectwindow.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlDatabase \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqldatabase.h \
		DatabaseUtils.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlDriver \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqldriver.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlError \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqlerror.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlQuery \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqlquery.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/QSettings \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/qsettings.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/qmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lopatool.o lopatool.cpp

newprojectwindow.o: newprojectwindow.cpp newprojectwindow.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlDatabase \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqldatabase.h \
		DatabaseUtils.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlDriver \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqldriver.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlError \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqlerror.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/QSqlQuery \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtSql.framework/Headers/qsqlquery.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/QSettings \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/qsettings.h \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt/6.1.2/lib/QtCore.framework/Headers/qmap.h \
		ui_newprojectwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newprojectwindow.o newprojectwindow.cpp

qrc_assets.o: qrc_assets.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_assets.o qrc_assets.cpp

moc_lopatool.o: moc_lopatool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lopatool.o moc_lopatool.cpp

moc_newprojectwindow.o: moc_newprojectwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newprojectwindow.o moc_newprojectwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/LOPATool/bin || mkdir -p $(INSTALL_ROOT)/opt/LOPATool/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/LOPATool/bin/LOPATool.app
	
	$(QINSTALL) LOPATool.app $(INSTALL_ROOT)/opt/LOPATool/bin/LOPATool.app
	-$(STRIP) $(INSTALL_ROOT)/opt/LOPATool/bin/LOPATool.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/LOPATool/bin/LOPATool.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/LOPATool/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

